# Generated by Django 4.0.3 on 2022-03-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_study_delete_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='user',
            new_name='user_id',
        ),
    ]
